import { Box, GlobalStyles, ThemeProvider } from '@mui/material';
import { theme } from '../themes/Theme';
import { SideMenu } from '@/components/menu-lateral/side-menu';
import { DrawerProvider } from '@/components/menu-lateral/drawerContext';
import Header from '@/components/header/header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <body>
        <ThemeProvider theme={theme}>
          <DrawerProvider>
            <GlobalStyles styles={{ '*': { boxSizing: 'border-box' } }} />
            <Box sx={{ display: 'flex' }}>
              <SideMenu />
              <Box
                component="main"
                sx={{
                  flexGrow: 1,

                }}
              >
                <Header />
                {children}
              </Box>
            </Box>
          </DrawerProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
