import { Box, CssBaseline, GlobalStyles } from '@mui/material';

import { DrawerProvider } from '@/components/menu-lateral/drawerContext';

import { ThemeContextProvider } from '@/themes/themeContext';

export const metadata = {
  title: 'Blue - Você é a nossa pessoa!',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt">
      <head>
        <link rel="icon" href="/favicon.svg" />
      </head>
      <body>
        <ThemeContextProvider>
          <CssBaseline />
          <DrawerProvider>
            <GlobalStyles styles={{ '*': { boxSizing: 'border-box' } }} />
            {children}
          </DrawerProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}

